language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.8
  - pypy
env:
  - DJANGO="<2.1"
  - DJANGO="<2.2"
  - DJANGO="<2.3"
  - DJANGO="<3.1"
before_install:
  - export DJANGO_SETTINGS_MODULE=jet.tests.settings
install:
  - pip3 install -q "Django${DJANGO}"
  - pip3 install .
  - pip3 install coverage==3.7.1
  - pip3 install coveralls==0.5
script:
  - coverage run --source=jet --omit=*/migrations/*,*/south_migrations/*,*/tests/* manage.py test jet
after_success:
  - coverage report
  - coveralls
matrix:
  exclude:
    - python: 3.3
      env: DJANGO="<2.1"
    - python: 3.3
      env: DJANGO="<2.2"
    - python: 3.3
      env: DJANGO="<2.3"
    - python: 3.3
      env: DJANGO="<3.1"

    - python: 3.5
      env: DJANGO="<2.1"
    - python: 3.5
      env: DJANGO="<2.2"
    - python: 3.5
      env: DJANGO="<2.3"
    - python: 3.5
      env: DJANGO="<3.1"

    - python: 3.6
      env: DJANGO="<2.1"
    - python: 3.6
      env: DJANGO="<2.2"
    - python: 3.6
      env: DJANGO="<2.3"
    - python: 3.6
      env: DJANGO="<3.1"

    - python: 3.8
      env: DJANGO="<2.1"
    - python: 3.8
      env: DJANGO="<2.2"
    - python: 3.8
      env: DJANGO="<2.3"
    - python: 3.8
      env: DJANGO="<3.1"

    - python: pypy
      env: DJANGO="<3.1"
